---
version: "3.3"

services:
 # the stackdef server itself
  virtualizer:
    # build and internals
    build:
        image: golang        
    #   context: .
    #   dockerfile: Dockerfile
    command: ["/main"]
    ports:
      - "8080:8080"
