version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/var/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/var/db/mongo
        ports:
            - 27017:27017
        command: mongod --smallfiles #--logpath=/dev/null # --quiet
