version: '3.4'
services:
  virtualizer:
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["./virt"]
    links:
      - mongodb
    ports:
      - '8080:8080'
    environment:
      MONGO_DB_URL: "mongodb://mongodb:27017"
    volumes:
    - ./data:/tmp/virtualizer
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/var/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - './data/db:/var/db/mongo'
    ports:
      - '27017:27017'
    command: 'mongod --smallfiles'
